version: '3.7'

services: 
  web: 
    build: './frontend'
    restart: always
    networks:
      net:
        aliases:
          - web    
    ports: 
      - "80:80" 
    container_name: web
    hostname: web   


networks:
  net:
    driver: bridge